# Generated by Django 6.0.3 on 2026-04-01 23:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='job_type',
            field=models.CharField(blank=True, choices=[('plumbing', 'Plumbing'), ('electrical', 'Electrical'), ('painting', 'Painting'), ('yard', 'Yard Work'), ('assembly', 'Furniture Assembly'), ('maintenance', 'General Maintenance'), ('other', 'Other')], default='other', max_length=50),
        ),
        migrations.AddField(
            model_name='post',
            name='location',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='post',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to=settings.AUTH_USER_MODEL),
        ),
    ]
