# Generated by Django 6.0.2 on 2026-03-06 03:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_post_created_by_post_job_type_post_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='created_by',
        ),
    ]
