# Generated by Django 6.0.2 on 2026-05-03 05:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_savedpost'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='accepted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='accepted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accepted_jobs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='post',
            name='status',
            field=models.CharField(choices=[('open', 'Open'), ('accepted', 'Accepted'), ('completed', 'Completed')], default='open', max_length=20),
        ),
        migrations.AlterField(
            model_name='savedpost',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
