# Generated by Django 6.0.2 on 2026-05-03 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_post_accepted_at_post_accepted_by_post_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='pay_rate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
